project_id = "lvvtlseiwrnrvrmenche"

[functions.feature-ad-payment]
verify_jwt = true

[functions.verify-featured-payment]
verify_jwt = true

[functions.cleanup-expired-featured]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false